### ISSUE TITLE
GroupBy usage with tags

### ISSUE THREAD

**Issue by 4nte** [benjamin658/influx-query-builder#3]
GroupBy currently supports only time periods (`GROUP BY time()`)
I suggest that we introduce `QueryBuilder.GroupByTag()` and `QueryBuilder.GroupByTime()` for clarity.

Also `GroupByTime` could accept `time.Duration` as a param instead of a string.

What do you think?

**Comment by benjamin658** [comment]
Hi, thank you for your recommendation, I think it is a good idea to enhance and clarify the GroupBy method.

I have already made this PR to enhance this feature #5 , you can see the usage of the `GroupByTime`  and  `GroupByTag` in README or in test case.

**Comment by 4nte** [comment]
Beautiful! Thanks for the efforts, the lib is very useful.
